# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
MidasBetaC <- function(nlag, param1, param2) {
    .Call('_MidasQuantR_MidasBetaC', PACKAGE = 'MidasQuantR', nlag, param1, param2)
}

