# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MidasBetaC <- function(nlag, param1, param2) {
    .Call('_MidasQuantR_MidasBetaC', PACKAGE = 'MidasQuantR', nlag, param1, param2)
}

#' @export
objFunC <- function(params, yr, Xr, q) {
    .Call('_MidasQuantR_objFunC', PACKAGE = 'MidasQuantR', params, yr, Xr, q)
}

#' @export
condQuantileC <- function(params, yr, Xr) {
    .Call('_MidasQuantR_condQuantileC', PACKAGE = 'MidasQuantR', params, yr, Xr)
}

GetIniParamsC <- function(yr, Xr, q, numInitialsRand = 10000L, numInitials = 10L) {
    .Call('_MidasQuantR_GetIniParamsC', PACKAGE = 'MidasQuantR', yr, Xr, q, numInitialsRand, numInitials)
}

